---
title: "Capstone Project"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
library(dplyr)
```

```{r}
IPO = read.csv("IPODataFull.csv")
```

```{r}
# fix typo
#IPO[IPO$Symbol=="EGL",]%>% select(c("exactDateFounded", "YearFounded"))
IPO[1040,"YearFounded"]=2011
IPO[IPO$Symbol=="EGL",]%>% select(c("exactDateFounded", "YearFounded"))
```


## Data Cleaning

```{r}
# default date in month
defaultDay = "15"
# default date in year
defaultDate ="06-30"
```

```{r,results='hide'}
# drop na in YearFounded
IPO = IPO[!is.na(IPO$YearFounded),]
# look at original datetime format
#IPO %>% select(c("ipoDate", "YearFounded", "exactDateFounded"))
```

```{r,results='hide'}
# reformat ipoDate into IPODate
IPO$IPODate = as.Date(IPO$ipoDate,format='%m/%d/%y %H:%M')
# drop ipoDate
IPO = subset(IPO, select = -ipoDate)
# look again
#IPO %>% select(c("IPODate", "YearFounded", "exactDateFounded"))
```

```{r}
# reformat exactDateFounded into DateFounded
DateFounded = c(Sys.Date())
for (i in 1:nrow(IPO)){
  rawDate = IPO$exactDateFounded[i]
  len = nchar(gsub('[^,]', '', rawDate)) +1L
  if (len==1){
    mydate = paste0(rawDate,defaultDate)
    DateFounded = c(DateFounded, as.Date(mydate,format='%Y%m-%d'))
  } else if (len==2){
    mydate = paste0(rawDate,defaultDay)
    DateFounded = c(DateFounded, as.Date(mydate,format='%B,%Y%d'))
  } else if (len==3){
    DateFounded = c(DateFounded, as.Date(rawDate,format="%B,%d,%Y"))
  } else if (len==4){
    DateFounded = c(DateFounded, as.Date("June,28,1951", format="%B,%d,%Y")) # I looked at this exception
  }
}
IPO$DateFounded = DateFounded[-1]
# drop exactDateFounded
IPO = subset(IPO, select = -exactDateFounded)
```

```{r}
# create DaysToIPO, IPOYear and YearsToIPO
IPO$DaysToIPO = as.numeric(difftime(IPO$IPODate, IPO$DateFounded, units = "days"))
IPO$IPOYear = format(IPO$IPODate,"%Y")
IPO$YearsToIPO = as.numeric(IPO$IPOYear) - as.numeric(IPO$YearFounded)
# Filter out negative DaysToIPO
IPO = IPO %>% filter(DaysToIPO >= 0)
# look again
#IPO %>% select(c("IPOYear", "IPODate", "YearFounded", "DateFounded", "DaysToIPO", "YearsToIPO"))
```

```{r}
# subset of the original data set without TVC or anything after Fiscal_year
IPO_sub <- select (IPO, Symbol, DaysToIPO, YearsToIPO, DaysBetterThanSP, daysProfit, daysProfitGrouped, LastSale, MarketCap, Sector, Industry, CEOTakeOver, CEOAge, CEOGender, PresidentAge, Revenue, netIncome, lastFiscalYearGrowth, employees)
```


```{r}
# make numeric Revenue
for (i in 1:nrow(IPO_sub)){
  x=gsub("\\$", "", IPO_sub$Revenue[i])
  if (endsWith(x,"B")){
    x<-as.numeric(gsub("B", "", x))
    x=x*1000000000
  }
  else if (endsWith(x,"M")){
    x<-as.numeric(gsub("M", "", x))
    x=x*1000000
  }
  IPO_sub$Revenue[i]<-x
}

# make numeric netIncome
for (i in 1:nrow(IPO_sub)){
  x=gsub("\\$", "", IPO_sub$netIncome[i])
  if (endsWith(x,"B")){
    x<-as.numeric(gsub("B", "", x))
    x=x*1000000000
  }
  else if (endsWith(x,"M")){
    x<-as.numeric(gsub("M", "", x))
    x=x*1000000
  }
  IPO_sub$netIncome[i]<-x
}
```

```{r,message=FALSE, warning=FALSE}
IPO_sub$Revenue<-as.numeric(IPO_sub$Revenue)
IPO_sub$netIncome<-as.numeric(IPO_sub$netIncome)
IPO_sub$lastFiscalYearGrowth<-as.numeric(IPO_sub$lastFiscalYearGrowth)
IPO_sub$employees<-as.numeric(IPO_sub$employees)
IPO_sub$daysProfitGrouped<-as.factor((IPO_sub$daysProfitGrouped))
IPO_sub$Sector<-as.factor((IPO_sub$Sector))
IPO_sub$Industry<-as.factor((IPO_sub$Industry))
IPO_sub$Symbol<-as.factor(IPO_sub$Symbol)
IPO_sub$CEOGender<- as.factor(IPO_sub$CEOGender)
summary(IPO_sub)
```

```{r, message=FALSE}
data<-select(IPO_sub,-Sector,-Industry,-daysProfitGrouped, -CEOGender, -Symbol)
library(pcalg)
suff_stat <- list(C = cor(data), n = nrow(data))
pc_data <- pc(suff_stat, indepTest = gaussCItest, labels = colnames(data), alpha = 0.05, skel.method = "stable.fast")
plot(pc_data, main = "pcalg graph",  cex.main=1.5, cex.sub=2.5)
```

## DaysToIPO as time

```{r,eval=FALSE}
library(survival)

m1 = coxph( Surv( DaysToIPO) ~ DaysBetterThanSP , data=IPO_sub )
plot( cox.zph(m1) )

m2 = coxph( Surv( DaysToIPO) ~ daysProfit , data=IPO_sub )
plot( cox.zph(m2) )

m3 = coxph( Surv( DaysToIPO) ~ Revenue , data=IPO_sub )
plot( cox.zph(m3) )

m4 = coxph( Surv( DaysToIPO) ~ netIncome , data=IPO_sub )
plot( cox.zph(m4) )

m5 = coxph( Surv( DaysToIPO) ~ CEOAge , data=IPO_sub )
plot( cox.zph(m5) )

m6 = coxph( Surv( DaysToIPO) ~ PresidentAge , data=IPO_sub )
plot( cox.zph(m6) )

m7 = coxph( Surv( DaysToIPO) ~ lastFiscalYearGrowth , data=IPO_sub )
plot( cox.zph(m7) )

m8 = coxph( Surv( DaysToIPO) ~ employees , data=IPO_sub )
plot( cox.zph(m8) )

m9 = coxph( Surv( DaysToIPO) ~ LastSale , data=IPO_sub )
plot( cox.zph(m9) )

m10 = coxph( Surv( DaysToIPO) ~ MarketCap , data=IPO_sub )
plot( cox.zph(m10) )
```

```{r}
cox.zph(m1) ## <  0.05
cox.zph(m2) ## >  0.05
cox.zph(m3) ## >  0.05
cox.zph(m4) ## >  0.05
cox.zph(m5) ## <  0.05
cox.zph(m6) ## <  0.05
cox.zph(m7) ## <  0.05
cox.zph(m8) ## <  0.05
cox.zph(m9) ## >  0.05
cox.zph(m10) ## <  0.05
```

```{r}
library(ggplot2)
ggplot(data=IPO_sub,aes(x=DaysBetterThanSP,y=DaysToIPO))+geom_point()+geom_smooth()
ggplot(data=IPO_sub,aes(x=daysProfit,y=DaysToIPO))+geom_point()+geom_smooth()
ggplot(data=IPO_sub,aes(x=LastSale,y=DaysToIPO))+geom_point()+geom_smooth()
ggplot(data=IPO_sub,aes(x=MarketCap,y=DaysToIPO))+geom_point()+geom_smooth()
```

```{r}
ggplot(data=IPO_sub,aes(x=DaysBetterThanSP,y=DaysToIPO,color=factor(daysProfitGrouped)))+geom_point()+geom_smooth()

# Alternatively
ggplot(IPO_sub,aes(x=DaysBetterThanSP,y=DaysToIPO)) +
    geom_boxplot() +
    facet_grid(~daysProfitGrouped)
```

```{r}
ggplot(data=IPO_sub,aes(x=MarketCap,y=DaysToIPO,color=factor(daysProfitGrouped)))+geom_point()+geom_smooth()

# Alternatively
ggplot(IPO_sub,aes(x=MarketCap,y=DaysToIPO)) +
    geom_boxplot() +
    facet_grid(~daysProfitGrouped)
```

```{r}
ggplot(data=IPO_sub,aes(x=LastSale,y=DaysToIPO,color=factor(daysProfitGrouped)))+geom_point()+geom_smooth()

# Alternatively
ggplot(IPO_sub,aes(x=LastSale,y=DaysToIPO)) +
    geom_boxplot() +
    facet_grid(~daysProfitGrouped)
```

### Some models

```{r}
md1=coxph(Surv(DaysToIPO)~daysProfit+Revenue+netIncome+LastSale,data=IPO_sub)
summary(md1)
```

```{r}
md2=survreg(Surv(DaysToIPO)~daysProfit+Revenue+netIncome+LastSale,data=IPO_sub,dist="gaussian")
summary(md2)
```

```{r}
md3=survreg(Surv(DaysToIPO+0.0001)~daysProfit+Revenue+netIncome+LastSale,data=IPO_sub,dist="exponential")
summary(md3)
```

```{r}
md4=survreg(Surv(DaysToIPO+0.0001)~daysProfit+Revenue+netIncome+LastSale,data=IPO_sub,dist="weibull")
summary(md4)
```

```{r}
md5=survreg(Surv(DaysToIPO+0.0001)~daysProfit+Revenue+netIncome+LastSale,data=IPO_sub,dist="lognormal")
summary(md5)
```

### Model comparison

```{r}

```

## YearsToIPO as time

```{r}

```
